// IMPORTANT: DO NOT EDIT THIS FILE MANUALLY!
// This file is automatically generated with `cargo xtask codegen`.
// To make any changes, edit the xtask source instead.

//! Combined re-exports of all Minecraft version submodules in the type-specific modules.

/// Re-exports for all items of the latest Minecraft version.
#[cfg(feature = "latest")]
#[rustfmt::skip]
pub mod latest {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::latest::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::latest::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::latest::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::latest::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::latest::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::latest::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::latest::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.14.
#[cfg(feature = "1.14")]
#[rustfmt::skip]
pub mod mc1_14 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_14::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_14::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_14::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_14::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_14::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_14::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_14::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.15.
#[cfg(feature = "1.15")]
#[rustfmt::skip]
pub mod mc1_15 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_15::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_15::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_15::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_15::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_15::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_15::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_15::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.15.2.
#[cfg(feature = "1.15.2")]
#[rustfmt::skip]
pub mod mc1_15_2 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_15_2::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_15_2::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_15_2::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_15_2::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_15_2::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_15_2::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_15_2::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.16.
#[cfg(feature = "1.16")]
#[rustfmt::skip]
pub mod mc1_16 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_16::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_16::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_16::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_16::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_16::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_16::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_16::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.16.2.
#[cfg(feature = "1.16.2")]
#[rustfmt::skip]
pub mod mc1_16_2 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_16_2::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_16_2::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_16_2::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_16_2::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_16_2::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_16_2::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_16_2::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.17.
#[cfg(feature = "1.17")]
#[rustfmt::skip]
pub mod mc1_17 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_17::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_17::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_17::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_17::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_17::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_17::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_17::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.18.
#[cfg(feature = "1.18")]
#[rustfmt::skip]
pub mod mc1_18 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_18::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_18::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_18::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_18::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_18::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_18::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_18::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.19.
#[cfg(feature = "1.19")]
#[rustfmt::skip]
pub mod mc1_19 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_19::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.19.1.
#[cfg(feature = "1.19.1")]
#[rustfmt::skip]
pub mod mc1_19_1 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_19_1::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_1::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_1::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_1::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_1::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_1::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_1::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.19.3.
#[cfg(feature = "1.19.3")]
#[rustfmt::skip]
pub mod mc1_19_3 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_19_3::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_3::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_3::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_3::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_3::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_3::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_3::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.19.4.
#[cfg(feature = "1.19.4")]
#[rustfmt::skip]
pub mod mc1_19_4 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_19_4::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_4::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_4::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_19_4::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_4::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_4::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_19_4::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.20.
#[cfg(feature = "1.20")]
#[rustfmt::skip]
pub mod mc1_20 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_20::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.20.2.
#[cfg(feature = "1.20.2")]
#[rustfmt::skip]
pub mod mc1_20_2 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_20_2::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_2::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_2::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_2::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_2::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_2::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_2::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.20.3.
#[cfg(feature = "1.20.3")]
#[rustfmt::skip]
pub mod mc1_20_3 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_20_3::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_3::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_3::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_3::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_3::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_3::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_3::compounds as block_entity_compounds;
}

/// Types for Minecraft 1.20.5.
#[cfg(feature = "1.20.5")]
#[rustfmt::skip]
pub mod mc1_20_5 {
    #[cfg(feature = "block-states")]
    pub use crate::block_state::list::mc1_20_5::*;

    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_5::Entity;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_5::types as entity_types;
    #[cfg(feature = "entities")]
    pub use crate::entity::list::mc1_20_5::compounds as entity_compounds;

    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_5::BlockEntity;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_5::types as block_entity_types;
    #[cfg(feature = "block-entities")]
    pub use crate::block_entity::list::mc1_20_5::compounds as block_entity_compounds;
}
